version: '3.4'
services:

   db:
     image: postgres:10-alpine
     ports:
       - "5432"
       - "9432:5432"
     networks:
       - talkvoter_net
     volumes:
       - pgdata:/var/lib/postgresql/data/
     healthcheck:
       test: ["CMD", "pg_isready", "-U", "postgres"]
       start_period: 5s
       interval: 30s
       timeout: 10s
       retries: 3

   app:
     image: docker4data/talkvoter:prod-1.0.1
     build:
       context: .
       dockerfile: Dockerfile
     command: /app/docker-utils/run.sh
     volumes:
       - .:/app/proj/
       - static-volume:/app/htdocs/static/
     ports:
       - "8000:8000"
     environment:
       - DATABASE_URL=postgres://postgres@db/postgres
       - SITE_DIR=/app/
       - SECRET_KEY=super secret key
     networks:
       - talkvoter_net
     depends_on:
       - db
     stdin_open: true
     tty: true
     healthcheck:
       test: ["CMD", "curl", "localhost", "8000"]
       start_period: 5s
       interval: 30s
       timeout: 10s
       retries: 3

networks:
  talkvoter_net:

volumes:
  static-volume:
  pgdata:
